version: '3.4'

services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Users.API/Dockerfile
    depends_on:
      - nosql.data

  nosql.data:
    image: mongo